spring.application.name=kheera-backend

jwt.secret=${JWT_SECRET}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.url=${DB_SERVER}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=${PORT}

springdoc.swagger-ui.path=/api/swagger-ui.html
server.forward-headers-strategy=framework
X-Forwarded-Proto=https

#Email related properties

spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.localhost=localhost
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
