ALTER TABLE space_members
    ADD is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    ADD created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;